= OpenGarage mit Jeedom

OpenGarage ist ein Objekt des Typs DIY, welches die Steuerung ihrer Garage ermöglicht.

Es bietet die Aktivierung eines Relais (zum Öffnen der Garage) und einen Abstand Sensor, um das vorhanden sein des Autos zu überprüfen.

http://opengarage.io/

==  Auslesen der OpenGaragen Zustände

Um den Zustand des Relais und des Abstandssensors abzufrage, ist die folgende URL zu verwenden : 

----
http://addropengarage/jc
----

Das Ergebnis wird in JSON Form ausgegeben. Es ist daher notwendig, ein Gerät vom Typ Script und einen Info-Befehl vom Typ json zu verwenden.

Für Relais-Status den Name der JSON Eigenschaft : door

Für Distanzsensor : dist

== Aktionen für OpenGarage

Die Adresse für die Aktivierung des Relais lautet :

----
http://addropengarage/cc?dkey=xxxx&click=1
----

dkey ist der API-Schlüssel, standardmäßig ist es opendoor

== Weitere Informationen

Die vollständige Dokumentation der API ist auf github verfügbar :

https://github.com/OpenGarage/OpenGarage-Firmware/tree/master/docs